US_GB_DICT = {
    "bind": "cast",
    "gauge": "tension",
    "skip": "miss",
    "yarn over": "yarn over needle",
    "YO": "yarn over needle",
    "stockinette stitch": "stocking stitch",
    "seed stitch": "moss stitch",
    "selvage": "selvedge",
    "through the back loop": "through back of the loop",
    "yarn to the front": "wool forward",
    "yarn to the back": "wool back",
    "4-stitch left cable": "cable 4 front",
    "cross 4-stitches to the left": "cable 4 front",
    "C4L": "C4F",
    "4-stitch right cable": "cable 4 back",
    "cross 4-stitches to the right": "cable 4 back",
    "C4R": "C4B",
    "sl st" : "sl1k",
    "knit 2 together": "k2tog",
    "laceweight": "1 ply",
    "fingering": "2 ply",
    "sock": "3 ply",  # This may cause issues with descriptions involving an actual sock
    "sport": "4 ply", # This may cause issues with certain descriptions
    "light worsted": "DK",
    "lightly worsted": "DK",
    "worsted": "aran",
    "bulky": "chunky",
}